name: Auto
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install playwright requests python-dotenv pytz
        playwright install chromium

    - name: Jalankan Multi Script
      env:
        userid: ${{ secrets.USERID }}
        pw: ${{ secrets.PW }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python multi.py

    - name: Set WIB time
      id: set_wib_time
      run: |
        TIME_WIB=$(date -u --date='+7 hours' '+%Y-%m-%d %H:%M:%S')
        echo "time_wib=$TIME_WIB" >> $GITHUB_OUTPUT

    - name: Kirim Notifikasi Telegram (Success)
      if: success()
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="✅ Workflow *BERHASIL* pada ${{ steps.set_wib_time.outputs.time_wib }} WIB" \
          -d parse_mode="Markdown"

    - name: Kirim Notifikasi Telegram (Failed)
      if: failure()
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="❌ Workflow *GAGAL* pada ${{ steps.set_wib_time.outputs.time_wib }} WIB" \
          -d parse_mode="Markdown"
